apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ .Values.postgresql.existingSecret }}
spec:
  encryptedData:
    postgresql-password: AgBV80+5nVP1U1lD8Gtuymu44b8AimreBwEXPyv49RJ8PzKrd/IORfCY7sg5//v5yMNOVjQxqDb4YdMqUK3jRoUB5QRRHsI0o8I0Nq9zMKKMoviYHsMusO6wi5BIX73xbGwYhqXF9t2UeH8FgeeVUgO4Y4gdu8DlewdGCvWdZGWMlAYsuQV73d2nwPIBHZBNhcdHv4OH1iWyvijuS28ioAP91r96JQa4YHD+eWGj+VZBGBF2D8dAdjlS4UolChgkyWoCikQQnRBkkOMzft2YHjRFlcZUdA97B8yQ4hmE4BbfhWN3qMOQIMNY1AFFTkrZL0OUG4mvduI0SwMItc9NOrsGu6yB4S+WzwUbP7GTxIHAFJCDHjqkWrSOfWgDLzlxg+hy751rFcHeOvxAVWJvQ9D1q/ODDULlv6exngcNdiVVWoIuSbtPuKkxTIBGTQGCkB2jHOHgFNVeR6uncpunxjG8w0ALsKho9gYmK4foy5dFqqY9dtnxQkK/AhNn6+fOt4d15o9P9aDpuK9C+3ICLKzxyE3tHL0LtxsDBISODDiuQJTD8bB3MgppR+EH4ZxChDH2hi+CdOcCuVewYzEqfe6e3YDtfb5nBSZKDa0LCJjDO+eFKmj8AEdFhTyqGbnYKRM7/ak+sYrBEY3WB2NwMW5x+Od6azRkUFcMwM1zicL6E0bdokgJgmomH74X19/U5sOA/W0LLcJSIw==
    postgresql-postgres-password: AgBWDPIDbu4bUIRQjZdoBdsKyU8/4luVvE0vBPtpcXgGQLnbZtysKqLuBlRrur0LxhZVtfgRHTsqpdEzLdI9sjwUSQv3h2vEVv4NHkMWXeXYkB4QCfZAzDXMhTb+6VwaiLfk9PcguQMIH679SxuYJrL8+rGr+shnU5Ze0Zgcg71BZq+9LslXgg8/IjbJlql04pD1QIfyJEENjO7GlCEog1LHDSy/bLgK3s7Y4B+zclRmiP/ALbsVh0rseLcNdElkyiAogrgL7r788ISLU7F4ampo6g1/3JdPk4BXoSn79w6K/RgphrBLqn1duT/34LGulD8VxzxeYMyCvobfXoC4bYp9nJIsSIKVqIuwlQF8NhDQ+XnStqnss+RNe80YwljzcNvw/1aYB+mWddgb4qN0IOmcXenOu1B8E33pNIViliPot5dLeJsPm3aud6cprw7K82PW0mrkCpR2XHRp/Qv5rLJiANoM1oufdKZiwHYLYE/K9J33s10SiuJcQ+wSF5RD+qdUflor0bewEGr13OdjEjtGcPTXRw2t1ikQqBWkQKz2wdM2g8moTakqgGPpBvhU810684y0nPWVZwFhK1J5xIwhNvzYVWIgU+mgngIz/iXuC/OXzs2ie1u3IaVLmhtaZSNmb2CdZHKhNgzltBONLtWViH6fbYs7PH0bsm8VLlLU4+IQhlh1xauoF8lYxL5cPuWEaDmftEBVcsDv
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ .Values.postgresql.existingSecret }}
