apiVersion: v2
name: stakater-nordmart-inventory
description: A Helm chart for Kubernetes
dependencies:
- name: postgresql
  version: 9.1.4
  repository: "https://charts.bitnami.com/bitnami"
- name: application
  version: 1.1.7
  repository: https://stakater.github.io/stakater-charts  
  
# DON'T TOUCH THIS
# This is the chart version. This version number is incremented automatically each time you make changes
# to the application or helm values file; and pushed to artifact store
version: 0.0.0
