application:
  secretProviderClass:
    enabled: true
    name: inventory-postgres
    provider: vault
    roleName: '{{ .Release.Namespace }}'
    objects: |
      - objectName: "postgresql-passowrd"
        secretPath: "veeru/kv/data/inventory-postgres"
        secretKey: "postgresql-password"  
    secretObjects:
      - data:
        - key: postgresql-password
          objectName: postgresql-passowrd
        secretName: inventory-postgres
        type: Opaque 